import React from 'react';
import Productcard from '../UI/ProductCard';

const Featuredproducts = () => {
    return (
        <section id='featured'>
           <Productcard  title={"Arlo Ultra 2 | 4K Security Camera | 4K Wireless Camera System"}  
           desc={"For the ultimate protection rain or shine, see more of what's happening with an ultra-wide field of view and 4K video with HDR. Perfect for protecting any location where you need the biggest, best view."}
            src={"nice"} />

<Productcard  title={"TP-Link Deco X68(2-Pack) AX3600 Whole Home Mesh Wi-Fi 6 System"}  
desc={"Connect More Devices: Connect over 150 devices without dragging down performance Boosted Seamless Coverage: Achieve seamless whole-home coverage with a clearer and stronger whole-home Wi-Fi signal generated by Wi-Fi 6"}
src={"nice"} />

<Productcard  title={"KEYESTUDIO Smart Home Starter Kit for Arduino for Uno R3"}
  desc={"Designed for learning electronics and programming in a simple and fun way.KEYESTUDIO coding toy contains instructions to make 15 projects to learn about the basics of different modules like buttons, LEDs, sensors, etc., and learn how smart home works."}
            src={"nice"} />

<Productcard  title={"GL.iNet GL-X750 (Spitz) Version 2, 4G LTE OpenWrt VPN Router"}  
desc={"Comes with the redesigned PCBA and optimized antennas to improve the 4G performance. Transfer 4G LTE signal to Wi-Fi, with sim card slot, 300Mbps(2.4G)+433Mbps(5G) WiFi networking."}
            src={"nice"} />

<Productcard  title={"Eufy Security Floodlight Camera E with Built-in AI, 2K Resolution, 2-Way Audio"}  
desc={"Flawless 2K Surveillance: Live-stream and record in full 2K resolution and see exactly who’s there in crisp clarity"}
            src={"nice"} />

<Productcard  title={"360 Smart Home Camera Doorbell X3 with Wi-Fi Base Station"}  desc={"What’s amazing about the 360 Video Doorbell X3 is its radar sensor is equipped with ultra-precise quadruple AI detection. Their proprietary algorithms make it possible to distinguish between people and other movements such as falling leaves, cars passing by or animals so no false alarms will be triggered."}
            src={"nice"} />


        </section>
    );
}

export default Featuredproducts;
